apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: lab3
spec:
  resources:
    requests:
      storage: 4Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
